import type { Product, Order, AppUser, AppNotification } from "./types";

export const initialProducts: Product[] = [
  {
    id: "PROD-001",
    name: "หูฟัง Quantum ตัดเสียงรบกวนภายนอก",
    category: "Electronics",
    brand: "Quantum",
    price: 299.99,
    sales: 345,
    revenue: 103496.55,
    stock: 45,
    status: "In Stock",
  },
  {
    id: "PROD-002",
    name: "กระเป๋าเป้สะพายหลังกันน้ำ Urban Tech",
    category: "Apparel",
    brand: "Urban Tech",
    price: 89.0,
    sales: 812,
    revenue: 72268.0,
    stock: 120,
    status: "In Stock",
  },
  {
    id: "PROD-003",
    name: "โคมไฟอ่านหนังสืออัจฉริยะ Nordic Minimalist",
    category: "Home",
    brand: "Nordic",
    price: 124.5,
    sales: 520,
    revenue: 64740.0,
    stock: 8,
    status: "Low Stock",
  },
  {
    id: "PROD-004",
    name: "เซรั่มบำรุงผิวหน้าพรีเมียม Hydro-Glow",
    category: "Beauty",
    brand: "Hydro-Glow",
    price: 58.0,
    sales: 1105,
    revenue: 64090.0,
    stock: 0,
    status: "Out of Stock",
  },
  {
    id: "PROD-005",
    name: "หมอนรองคอเมมโมรี่โฟม Ergonomic",
    category: "Home",
    brand: "Ergonomic",
    price: 79.99,
    sales: 410,
    revenue: 32795.9,
    stock: 67,
    status: "In Stock",
  },
];

export const initialOrders: Order[] = [
  // 2026 Transactions (Active Range)
  {
    id: "ORD-89421",
    customerName: "อเล็กซานเดอร์ ไรท์",
    email: "alex@example.com",
    productName: "หูฟัง Quantum ตัดเสียงรบกวนภายนอก",
    brand: "Quantum",
    channel: "TikTok Shop",
    total: 299.99,
    quantity: 1,
    status: "Paid",
    date: "2026-06-02",
    shippingFee: 40,
    platformFee: 15,
    netIncome: 284.99,
  },
  {
    id: "ORD-89420",
    customerName: "โซเฟีย มาร์ติเนซ",
    email: "sophia.m@example.com",
    productName: "เซรั่มบำรุงผิวหน้าพรีเมียม Hydro-Glow",
    brand: "Hydro-Glow",
    channel: "Shopee",
    total: 58.0,
    quantity: 1,
    status: "Paid",
    date: "2026-06-02",
    shippingFee: 30,
    platformFee: 3.5,
    netIncome: 54.5,
  },
  {
    id: "ORD-89419",
    customerName: "มาร์คัส ทอมป์สัน",
    email: "marcus@example.com",
    productName: "กระเป๋าเป้สะพายหลังกันน้ำ Urban Tech",
    brand: "Urban Tech",
    channel: "Lazada",
    total: 89.0,
    quantity: 1,
    status: "Pending",
    date: "2026-06-01",
    shippingFee: 30,
    platformFee: 5.0,
    netIncome: 84.0,
  },
  {
    id: "ORD-89418",
    customerName: "โคลอี้ เบนเน็ต",
    email: "chloe@example.com",
    productName: "โคมไฟอ่านหนังสืออัจฉริยะ Nordic Minimalist",
    brand: "Nordic",
    channel: "Facebook",
    total: 124.5,
    quantity: 1,
    status: "Paid",
    date: "2026-06-01",
    shippingFee: 30,
    platformFee: 7.5,
    netIncome: 117.0,
  },
  {
    id: "ORD-89417",
    customerName: "แดเนียล คิม",
    email: "daniel@example.com",
    productName: "หูฟัง Quantum ตัดเสียงรบกวนภายนอก",
    brand: "Quantum",
    channel: "LINE OA",
    total: 599.98,
    quantity: 2,
    status: "Refunded",
    date: "2026-05-30",
    shippingFee: 50,
    platformFee: 36.0,
    netIncome: 563.98,
  },
  {
    id: "ORD-89416",
    customerName: "เอ็มม่า วัตสัน",
    email: "emma@example.com",
    productName: "เซรั่มบำรุงผิวหน้าพรีเมียม Hydro-Glow",
    brand: "Hydro-Glow",
    channel: "อื่นๆ",
    total: 58.0,
    quantity: 1,
    status: "Paid",
    date: "2026-05-29",
    shippingFee: 30,
    platformFee: 3.5,
    netIncome: 54.5,
  },

  // Historical 2025 Transactions
  {
    id: "ORD-85001",
    customerName: "จอน โด",
    email: "john.doe@example.com",
    productName: "หูฟัง Quantum ตัดเสียงรบกวนภายนอก",
    brand: "Quantum",
    channel: "TikTok Shop",
    total: 299.99,
    quantity: 1,
    status: "Paid",
    date: "2025-06-15",
    shippingFee: 40,
    platformFee: 15,
    netIncome: 284.99,
  },
  {
    id: "ORD-85002",
    customerName: "สมชาย นักพัฒนา",
    email: "somchai@phanvadee.io",
    productName: "กระเป๋าเป้สะพายหลังกันน้ำ Urban Tech",
    brand: "Urban Tech",
    channel: "Shopee",
    total: 89.0,
    quantity: 1,
    status: "Paid",
    date: "2025-11-20",
    shippingFee: 30,
    platformFee: 5.0,
    netIncome: 84.0,
  },
  {
    id: "ORD-85003",
    customerName: "ศิริพรรณ งามจิต",
    email: "siripan@example.com",
    productName: "โคมไฟอ่านหนังสืออัจฉริยะ Nordic Minimalist",
    brand: "Nordic",
    channel: "Lazada",
    total: 124.5,
    quantity: 1,
    status: "Pending",
    date: "2025-04-10",
    shippingFee: 30,
    platformFee: 7.5,
    netIncome: 117.0,
  },

  // Historical 2024 Transactions
  {
    id: "ORD-84001",
    customerName: "สมเจตน์ เจริญผล",
    email: "somjet@example.com",
    productName: "หมอนรองคอเมมโมรี่โฟม Ergonomic",
    brand: "Ergonomic",
    channel: "Facebook",
    total: 79.99,
    quantity: 1,
    status: "Paid",
    date: "2024-03-12",
    shippingFee: 30,
    platformFee: 4.5,
    netIncome: 75.49,
  },
  {
    id: "ORD-84002",
    customerName: "นรินทร์ แก้วดี",
    email: "narin@example.com",
    productName: "เซรั่มบำรุงผิวหน้าพรีเมียม Hydro-Glow",
    brand: "Hydro-Glow",
    channel: "LINE OA",
    total: 116.0,
    quantity: 2,
    status: "Paid",
    date: "2024-08-22",
    shippingFee: 40,
    platformFee: 8.0,
    netIncome: 108.0,
  },
  {
    id: "ORD-84003",
    customerName: "พัชรา เลิศยศ",
    email: "patchara@example.com",
    productName: "กระเป๋าเป้สะพายหลังกันน้ำ Urban Tech",
    brand: "Urban Tech",
    channel: "อื่นๆ",
    total: 89.0,
    quantity: 1,
    status: "Refunded",
    date: "2024-12-05",
    shippingFee: 30,
    platformFee: 5.0,
    netIncome: 84.0,
  },
];

export const initialUsersList: AppUser[] = [
  {
    id: "USR-001",
    name: "คุณภาณวดี",
    email: "phanvadee@phanvadee.io",
    username: "phanvadee",
    role: "Admin",
    status: "Active",
    password: "admin1234",
    tasks: ["ดูแดชบอร์ด", "ดูรายงานยอดขาย", "เครื่องคำนวณส่วนต่าง", "นำเข้าข้อมูล Excel", "จัดการผู้ใช้งาน"],
  },
  {
    id: "USR-002",
    name: "สมชาย นักพัฒนา",
    email: "somchai@phanvadee.io",
    username: "somchai",
    role: "Manager",
    status: "Active",
    password: "manager1234",
    tasks: ["ดูแดชบอร์ด", "ดูรายงานยอดขาย", "เครื่องคำนวณส่วนต่าง", "นำเข้าข้อมูล Excel", "จัดการผู้ใช้งาน"],
  },
  {
    id: "USR-003",
    name: "สมศรี เสมียนขาย",
    email: "somsri@phanvadee.io",
    username: "somsri",
    role: "User",
    status: "Active",
    password: "user1234",
    tasks: ["ดูรายงานยอดขาย", "เครื่องคำนวณส่วนต่าง"],
  },
  {
    id: "USR-004",
    name: "มาร์คัส พนักงานทั่วไป",
    email: "marcus@phanvadee.io",
    username: "marcus",
    role: "User",
    status: "Active",
    password: "user1234",
    tasks: ["นำเข้าข้อมูล Excel", "ดูรายงานยอดขาย"],
  },
  {
    id: "USR-005",
    name: "โซเฟีย ผู้ดูแลยอดขาย",
    email: "sophia@phanvadee.io",
    username: "sophia",
    role: "Manager",
    status: "Inactive",
    password: "user1234",
    tasks: ["ดูรายงานยอดขาย"],
  },
];

export const initialNotifications: AppNotification[] = [
  {
    id: "NOTIF-001",
    title: "อัปเดตสิทธิ์การใช้งานและการมอบหมายงาน",
    message: "ผู้จัดการ สมชาย ได้มอบหมายสิทธิ์งาน 'นำเข้าข้อมูล Excel' และ 'ดูรายงานยอดขาย' ให้กับคุณ",
    type: "task",
    targetRoles: ["User"],
    targetUserId: "USR-004",
    senderName: "สมชาย นักพัฒนา (Manager)",
    senderRole: "Manager",
    timestamp: "2026-06-02 10:30",
    readBy: [],
    actionTab: "sales",
    priority: "important",
  },
  {
    id: "NOTIF-002",
    title: "การนำเข้าไฟล์ข้อมูลสำเร็จ",
    message: "พนักงาน มาร์คัส ได้นำเข้าไฟล์ 'shopee_order.xlsx' จำนวน 150 รายการเข้าสู่ระบบเรียบร้อยแล้ว",
    type: "import",
    targetRoles: ["Admin", "Manager"],
    senderName: "มาร์คัส พนักงานทั่วไป",
    senderRole: "User",
    timestamp: "2026-06-02 11:15",
    readBy: [],
    actionTab: "sales",
    priority: "normal",
  },
  {
    id: "NOTIF-003",
    title: "แจ้งเตือนสินค้าใกล้หมดสต็อก",
    message: "สินค้า 'โคมไฟอ่านหนังสืออัจฉริยะ Nordic Minimalist' เหลือสต็อกเพียง 8 ชิ้น โปรดตรวจสอบการสั่งซื้อเพิ่ม",
    type: "inventory",
    targetRoles: ["Admin", "Manager", "User"],
    senderName: "ระบบตรวจเช็คคลังสินค้า",
    senderRole: "System",
    timestamp: "2026-06-02 11:45",
    readBy: [],
    actionTab: "dashboard",
    priority: "urgent",
  },
  {
    id: "NOTIF-004",
    title: "ประกาศ: ตรวจสอบและสรุปยอดขายประจำสัปดาห์",
    message: "ขอให้พนักงานและผู้จัดการทุกคนตรวจสอบความถูกต้องของรายการคำสั่งซื้อและรายงานส่วนต่างให้เรียบร้อยก่อนสิ้นสุดวันศุกร์นี้",
    type: "announcement",
    targetRoles: ["Admin", "Manager", "User"],
    senderName: "คุณภาณวดี (Admin)",
    senderRole: "Admin",
    timestamp: "2026-06-02 09:00",
    readBy: ["USR-001"],
    actionTab: "dashboard",
    priority: "important",
  },
  {
    id: "NOTIF-005",
    title: "สิทธิ์การเข้าถึงระบบเครื่องคำนวณส่วนต่าง",
    message: "คุณได้รับสิทธิ์เข้าใช้งานเครื่องคำนวณส่วนต่าง (Calculator) สำหรับคำนวณกำไรสุทธิและค่าธรรมเนียม",
    type: "task",
    targetRoles: ["User"],
    targetUserId: "USR-003",
    senderName: "คุณภาณวดี (Admin)",
    senderRole: "Admin",
    timestamp: "2026-06-01 14:20",
    readBy: [],
    actionTab: "calculator",
    priority: "normal",
  },
];

